### ISSUE TITLE
Analysis of Data from Hydrophobic Tubing Experiment 

### ISSUE THREAD

**Issue by Roswell-Lo** [AguaClara/high_g_flocculation#14]
![image](https://user-images.githubusercontent.com/31583357/36564306-d014c28a-17ea-11e8-85a7-e89f78d523a4.png)

After Testing both Hydrophobic and Regular tubing, there does not seem to be a significant difference in headloss accumulated throughout the experiments.   The effluent turbidity graphs showed that our coagulant worked similarly well in both trials.

**Comment by TanviNaidu** [comment]
Hi team! 
These graphs look great even though the result is not so delightful. 
Roswell, can you also upload the graph of headloss difference from Fall 2017 for comparison?

**Comment by monroews** [comment]
Could you plot the turbidity on a semilog plot so you can see how the turbidity is changing throughout the experiment?

Could you do some geometric modeling to see if we can figure out what is going on to cause this head loss? Is this head loss from coagulant nanoparticles or is this head loss from clay that is attaching to nanoparticles? You'd have to calculate the drag on these particles based on the average velocity as estimated from the velocity gradient at the wall.

Here is my hypothesis. Coagulant nanoparticles attach to the flocculator walls and they are so small that they don't cause any significant head loss. Eventually clay begins to attach to the coagulant nanoparticles. Perhaps this requires multiple coagulant nanoparticles close enough together so a clay particle can attach at multiple points.

They clay sticks out MUCH further into the flow and causes head loss AND captures more coagulant. So the increase in head loss as a function of time is proportional to how much clay is caught on the reactor wall. The amount of coagulant that is caught by the clay is proportional to the amount of clay on the wall which is proportional to the head loss. Thus the amount of coagulant that is lost to the walls is proportional to the head loss. 

Could you do some modeling of the head loss to see if any of these ideas make sense?

**Comment by Roswell-Lo** [comment]
![image](https://user-images.githubusercontent.com/31583357/36635335-0900d06a-1981-11e8-8c5e-4bfc9a2ac40d.png)

Here is last semester's pressure graph. It was at 300 G, but normal coagulant dose.   We were able to use the needle valve to damp the oscillations in pressure further, giving us a smoother line for this semester's experiments.

**Comment by Roswell-Lo** [comment]
![image](https://user-images.githubusercontent.com/31583357/36635454-e598bdc0-1982-11e8-9eb9-1bfed6ac5172.png)

Semi-log plots for effluent turbidity.  Looks linear with very slight increase until we run out of coagulant at the end of the experiment. Not sure what to attribute the increase to, but it could be from the sed tank being more slowly filled with more flocs.

**Comment by monroews** [comment]
When did the coagulant end? I realize that I misinterpreted the effluent turbidity results because I thought that the increasing turbidity was due to coagulant loss to the flocculator walls.  Did the coagulant run out around 7 hours? 

We need to develop better ways of plotting and discussing our data so that it is clearer what the data trends mean.

**Comment by monroews** [comment]
When you are discussing the linear increase, which part of the plot are you referring to?
If there is data from after the coagulant was turned off, then remove that part of the plot to eliminate confusion.
Our primary hypothesis is that coagulant attachment to the walls increases when the walls become partially covered with clay.

**Comment by monroews** [comment]
Can you measure the shear (flow rate) required to remove the attached particles and return the head loss to the initial value?

**Comment by Roswell-Lo** [comment]
Will update graphs to cut off before experiment runs out of coagulant.
